apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ratty-gopher-go 
  janus-idp.io/tekton: ratty-gopher-go
  backstage.io/kubernetes-id: ratty-gopher-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ratty-gopher-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  